spring:
  application:
    name: mylabel
  datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: 1234
      url: jdbc:mysql://localhost:3306/label?useSSL=false&serverTimezone=UTC&characterEncoding=utf-8




eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8779
