
spring:
  datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: 1234
      url: jdbc:mysql://localhost:3306/user?useSSL=false&serverTimezone=UTC&characterEncoding=utf-8
  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1
feng:
  filepath: file:/c:/fileupload/
management:
  endpoints:
    web:
      exposure:
        include: refresh,health,info
  server:
    port: 8778
ribbon:
  eureka:
    enabled: true
server:
  port: 8763
